# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe0c0efad111167295fe8e2c4bd6e378b8dce170820684e0821474fff537c0b1c437d44c5172eefbb8fb2e1fbdd693fc7988cf387981488733f5060ef5ad2b5

test:
  secret_key_base: 60b5bc2729e117e20070c98a16ad24d26d88bff620cfddfdff7b0365f16fd106e6f4bd6555672d28d3bc6ec7ec9a725e35f504446d9aee4bf71e365d5616d946

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
